CREATE USER IF NOT EXISTS "SA" SALT '36e124df91593af0' HASH 'c1d5405eb6f1c737275cc518155708d201d5a3f15acbf4f7345a2e0324c09285' ADMIN;

CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_MEDIA_ID" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_CUSTOMER_ID" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_LOAN_ID" START WITH 1 BELONGS_TO_TABLE;

CREATE TABLE "PUBLIC"."BOOK_AUTHORS"(
    "BOOK_ID" INTEGER NOT NULL,
    "AUTHORS" VARCHAR(255)
);

CREATE TABLE "PUBLIC"."BORROWABLE"(
    "SIGNATURE" VARCHAR(255) NOT NULL,
    "IS_AVAILABLE" BOOLEAN,
    "MEDIA_ID" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."BORROWABLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("SIGNATURE");

CREATE TABLE "PUBLIC"."CUSTOMER"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_CUSTOMER_ID" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_CUSTOMER_ID",
    "ADDRESS" VARCHAR(255),
    "NAME" VARCHAR(255) NOT NULL
);
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");

CREATE TABLE "PUBLIC"."CUSTOMER_FEE_PAYED_DATE"(
    "CUSTOMER_ID" INTEGER NOT NULL,
    "FEE_PAYED_DATE" TIMESTAMP,
    "FEE_PAYED_DATE_KEY" VARCHAR(32) NOT NULL
);
ALTER TABLE "PUBLIC"."CUSTOMER_FEE_PAYED_DATE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("CUSTOMER_ID", "FEE_PAYED_DATE_KEY");

CREATE TABLE "PUBLIC"."LOAN"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_LOAN_ID" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_LOAN_ID",
    "DUE_DATE" TIMESTAMP,
    "LOAN_DATE" TIMESTAMP,
    "CUSTOMER_ID" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."LOAN" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");

CREATE TABLE "PUBLIC"."LOAN_MEDIA_INSTANCES_IN_LOAN"(
    "LOAN_ID" BIGINT NOT NULL,
    "BORROWABLE_SIGNATURE" VARCHAR(255) NOT NULL
);

CREATE TABLE "PUBLIC"."MEDIA"(
    "DTYPE" VARCHAR(31) NOT NULL,
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_MEDIA_ID" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_MEDIA_ID",
    "TITLE" VARCHAR(255),
    "PRODUCER" VARCHAR(255),
    "STORAGE_TYPE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_45" PRIMARY KEY("ID");

ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."UNIQUE_CUSTOMER_NAME" UNIQUE("NAME");
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."UNIQUE_MEDIA_TITLE" UNIQUE("TITLE");
ALTER TABLE "PUBLIC"."CUSTOMER_FEE_PAYED_DATE" ADD CONSTRAINT "PUBLIC"."FK_CUSTOMER_FEE_PAYED_DATE_CUSTOMER_ID" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."CUSTOMER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BORROWABLE" ADD CONSTRAINT "PUBLIC"."FK_BORROWABLE_MEDIA_ID" FOREIGN KEY("MEDIA_ID") REFERENCES "PUBLIC"."MEDIA"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."LOAN_MEDIA_INSTANCES_IN_LOAN" ADD CONSTRAINT "PUBLIC"."FK_LOAN_MEDIA_INSTANCES_IN_LOAN_BORROWABLE_SIGNATURE" FOREIGN KEY("BORROWABLE_SIGNATURE") REFERENCES "PUBLIC"."BORROWABLE"("SIGNATURE") NOCHECK;
ALTER TABLE "PUBLIC"."LOAN" ADD CONSTRAINT "PUBLIC"."FK_LOAN_CUSTOMER_ID" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."CUSTOMER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BOOK_AUTHORS" ADD CONSTRAINT "PUBLIC"."FK_BOOK_AUTHORS_BOOK_ID" FOREIGN KEY("BOOK_ID") REFERENCES "PUBLIC"."MEDIA"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."LOAN_MEDIA_INSTANCES_IN_LOAN" ADD CONSTRAINT "PUBLIC"."FK_LOAN_MEDIA_INSTANCES_IN_LOAN_LOAN_ID" FOREIGN KEY("LOAN_ID") REFERENCES "PUBLIC"."LOAN"("ID") NOCHECK;
